/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import Model.Adicao;
import Model.Modificacao;
import Model.Remocao;
import Model.RemocaoSelecao;
import java.io.File;

/**
 *
 * @author cleyb
 */
public class Texto extends javax.swing.JFrame implements Runnable {

    private Controller controller;
    private String nome;
    private int position, selecao;
    //private AtualizacaoPeriodica ap;

    /**
     * Creates new form Texto
     */
    public Texto(String nome, Controller controller) {
        this.nome = nome;
        setTitle(nome);
        this.controller = controller;
        initComponents();
        jTextArea1.setText(controller.abrirArquivo(nome));
        //this.ap = new AtualizacaoPeriodica(System.currentTimeMillis(), this);
        //new Thread(ap).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        controller.fechar();
        new EscolherArquivo(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        //this.ap.atualiza(); //atualizar o tempo do loop
        selecao = 0;
        char tecla = evt.getKeyChar();
        int code = evt.getKeyCode(); //pega o valor inteiro da tecla pressionada
        if ((code == 0 || code == 32 || code == 10 || code > 43) && code != 127) {
            this.position = jTextArea1.getCaretPosition();
            controller.escreveArquivo(nome, tecla, this.position);
            System.out.println("tecla valida: " + code);
        }
        String textoSelecionado = jTextArea1.getSelectedText();
        if (textoSelecionado != null) {
            controller.del(nome, jTextArea1.getSelectionStart(), jTextArea1.getSelectionEnd());
            selecao = jTextArea1.getSelectionEnd() - jTextArea1.getSelectionStart();
        } else if (code == 8) {
            this.position = jTextArea1.getCaretPosition();
            if (this.position - 1 >= 0) {
                controller.del(nome, jTextArea1.getCaretPosition() - 1);
            }
        } else if (code == 127) {
            this.position = jTextArea1.getCaretPosition();
            if (this.position < jTextArea1.getText().length()) {
                controller.del(nome, jTextArea1.getCaretPosition());
            }
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        int code = evt.getKeyCode();
        if ((code == 0 || code == 32 || code == 10 || code > 43) && code != 127) {
            this.position = jTextArea1.getCaretPosition();
        } else if (code == 8) {
            System.out.println("teste: " + jTextArea1.getSelectedText());
            this.position = jTextArea1.getCaretPosition();
            //jTextArea1.setCaretPosition(this.position);
        } else if (code == 127) {
            this.position = jTextArea1.getCaretPosition();
        } else {
            this.position = jTextArea1.getCaretPosition();
        }
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Volte sempre, Saindo");
        controller.fechar();
    }//GEN-LAST:event_formWindowClosing

    public void atualizarTextArea() {
        //int position = jTextArea1.getCaretPosition();
        //jTextArea1.setText(controller.refresh(nome));
        System.out.println("atualizou");
        //jTextArea1.setCaretPosition(position);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        System.out.println("Abrindo arquivo");
        int i = 1;
        while (controller.getTitulo() != null) {
            Modificacao operacoes = controller.requisicao();
            if (operacoes != null) {
                System.out.println("requivisao " + i);
                if (operacoes instanceof Adicao) {
                    Adicao add = (Adicao) operacoes;
                    if (add.getPosition() >= jTextArea1.getCaretPosition()) {
                        StringBuilder t = new StringBuilder(jTextArea1.getText());
                        t.append(add.getConteudo());
                        int carent = jTextArea1.getCaretPosition();
                        jTextArea1.setText(t.toString());
                        jTextArea1.setCaretPosition(carent);
                    } else {
                        StringBuilder t = new StringBuilder(jTextArea1.getText());
                        t.insert(add.getPosition(), add.getConteudo());
                        int carent = jTextArea1.getCaretPosition();
                        jTextArea1.setText(t.toString());
                        jTextArea1.setCaretPosition(carent + 1);
                    }

                } else if (operacoes instanceof Remocao) {
                    Remocao del = (Remocao) operacoes;
                    StringBuilder texto = new StringBuilder(jTextArea1.getText());
                    texto.deleteCharAt(del.getPosition());
                    int carent = jTextArea1.getCaretPosition();
                    jTextArea1.setText(texto.toString());
                    if (carent == 0 || carent > texto.length()) {
                        jTextArea1.setCaretPosition(jTextArea1.getText().length());
                    } else {
                        jTextArea1.setCaretPosition(carent);
                    }

                } else {
                    RemocaoSelecao del = (RemocaoSelecao) operacoes;
                    StringBuilder texto = new StringBuilder(jTextArea1.getText());
                    texto.delete(del.getPosBegin(), del.getPosEnd());
                    int carent = jTextArea1.getCaretPosition();
                    jTextArea1.setText(texto.toString());
                    if (carent == 0 || carent > texto.length()) {
                        jTextArea1.setCaretPosition(jTextArea1.getText().length());
                    } else {
                        jTextArea1.setCaretPosition(carent);
                    }
                }
            }
        }
        System.out.println("Fechou thread");
    }

}
