/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;

/**
 *
 * @author cleyb
 */
public class Texto extends javax.swing.JFrame {

    private Controller controller;
    private String nome;
    private int position;
    //private AtualizacaoPeriodica ap;

    /**
     * Creates new form Texto
     */
    public Texto(String nome, Controller controller) {
        this.nome = nome;
        setTitle(nome);
        this.controller = controller;
        initComponents();
        jTextArea1.setText(controller.abrirArquivo(nome));
        //this.ap = new AtualizacaoPeriodica(System.currentTimeMillis(), this);
        //new Thread(ap).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        new EscolherArquivo(controller).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        //this.ap.atualiza(); //atualizar o tempo do loop
        char tecla = evt.getKeyChar();
        int code = evt.getKeyCode(); //pega o valor inteiro da tecla pressionada

        if (code == 8) {
            this.position = jTextArea1.getCaretPosition();
            if (this.position - 1 >= 0) {
                controller.del(nome, jTextArea1.getSelectionStart(), jTextArea1.getSelectionEnd());
            }
        } else if (code == 0 || code == 32 || code == 10 || code > 43) {
            this.position = jTextArea1.getCaretPosition();
            controller.escreveArquivo(nome, tecla, this.position);
            System.out.println("tecla valida: " + code);
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        // TODO add your handling code here:
        char tecla = evt.getKeyChar();
        int code = evt.getKeyCode();
        if (code == 0 || code == 32 || code == 10 || code > 43) {
            jTextArea1.setText(controller.refresh(this.nome));
            jTextArea1.setCaretPosition(this.position + 1);
        } else if (code == 8) {
            if (this.position > 0) {
                this.position = this.position - 1;
            }
            jTextArea1.setCaretPosition(this.position);
        } else {
            this.position = jTextArea1.getCaretPosition();
            jTextArea1.setText(controller.refresh(this.nome));
            jTextArea1.setCaretPosition(this.position);
        }
    }//GEN-LAST:event_jTextArea1KeyReleased

    public void atualizarTextArea() {
        //int position = jTextArea1.getCaretPosition();
        jTextArea1.setText(controller.refresh(nome));
        System.out.println("atualizou");
        //jTextArea1.setCaretPosition(position);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

}
